"""empty message

Revision ID: ea3bfcc06bb4
Revises: 
Create Date: 2022-04-06 08:34:27.402224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea3bfcc06bb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salgados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # op.drop_table('users')
    # op.drop_table('invoices')
    # op.drop_table('orders')
    # op.drop_table('ka_series')
    # op.drop_table('product_model')
    # op.drop_table('usuarios')
    # op.drop_table('times')
    # op.drop_table('situacao')
    # op.drop_table('marca')
    # op.drop_table('animes')
    # op.drop_table('enderecos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('enderecos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='enderecos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('animes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('anime', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('released_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('seasons', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='animes_pkey'),
    sa.UniqueConstraint('anime', name='animes_anime_key')
    )
    op.create_table('marca',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_marca')
    )
    op.create_table('situacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_situacao')
    )
    op.create_table('times',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nome_do_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('divisao', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='times_pkey')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apelido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('endereco_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endereco_id_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endereco_id_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], name='usuarios_endereco_id_fkey'),
    sa.ForeignKeyConstraint(['endereco_id_2'], ['enderecos.id'], name='usuarios_endereco_id_2_fkey'),
    sa.ForeignKeyConstraint(['endereco_id_3'], ['enderecos.id'], name='usuarios_endereco_id_3_fkey'),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey')
    )
    op.create_table('product_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=244), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_model_pkey')
    )
    op.create_table('ka_series',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('serie', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('seasons', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('released_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('imdb_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ka_series_pkey'),
    sa.UniqueConstraint('serie', name='ka_series_serie_key')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_order_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name='orders_customer_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('released_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='invoices_order_id_fkey'),
    sa.PrimaryKeyConstraint('invoice_id', name='invoices_pkey'),
    sa.UniqueConstraint('invoice_number', name='invoices_invoice_number_key'),
    sa.UniqueConstraint('order_id', name='invoices_order_id_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('birthdata', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('children', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('married', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('account_balance', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_table('salgados')
    # ### end Alembic commands ###
